install:
  - go install github.com/ribacq/tomato

script:
  - ls
  - mv * laitues
  - tomato laitues

deploy:
  provider: pages
  local-dir: laitues_html
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
