language: go

go:
  - "1.10.x"

install:
  - go get github.com/ribacq/tomato

script:
  - mv * laitues
  - tomato laitues

deploy:
  provider: pages
  local-dir: laitues_html
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
