language: go

go:
  - "1.10.x"

install:
  - go get github.com/ribacq/tomato

script:
  - tomato .

deploy:
  provider: pages
  local-dir: ._html
  target-branch: master
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: src
