dist: trusty
sudo: false

before_install:
  - gimme 1.8.3
  - go version

install:
  - go version
  - gimme 1.8.3
  - ls
  - gimme -l
  - go get github.com/ribacq/tomato

script:
  - ls
  - mv * laitues
  - tomato laitues

deploy:
  provider: pages
  local-dir: laitues_html
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
